<a href="/" class="btn">Back</a>
<?php
if ($products->count() > 0) {
    ?>
   
    <a href="#" class="nav-link" id="user" ><h4>Products</h4></a>
    <div id="userdiv">
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Tags</th>
            <th>Price</th>
            <th>Stock</th>
            
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Product quantity: <?php echo $products->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($products as $product) { ?>
            <tr>
                <td><?php echo $product->id; ?></td>
                <td><?php echo $product->name; ?></td>
                <td><?php echo $product->description ?></td>  
                <td><?php echo $product->tags ?></td>  
                <td><?php echo $product->price ?></td>  
                <td><?php echo $product->stock ?></td>  

                
        <?php } ?>
        </tbody>
    </table>
    </div>

    <?php
}

?>
