<?php echo $this->locale->_('hi-name', ['name' => $user]);?><br>
<a class="btn " href="addproduct?bearer=<?php echo $_GET['bearer'] ?>" ><?php  echo  $this->locale->_('add product'); ?></a><br>
<a class="btn " href="products?bearer=<?php echo $_GET['bearer'] ?>" ><?php  echo  $this->locale->_('product'); ?></a><br>
<a class="btn " href="neworder?bearer=<?php echo $_GET['bearer'] ?>" ><?php  echo  $this->locale->_('new order'); ?></a><br>
<a class="btn " href="orders?bearer=<?php echo $_GET['bearer'] ?>" ><?php  echo  $this->locale->_('orders'); ?></a><br>
<a class="btn " href="settings?bearer=<?php echo $_GET['bearer'] ?>" ><?php  echo  $this->locale->_('settings'); ?></a><br>
<a class="btn " href="component?bearer=<?php echo $_GET['bearer'] ?>" ><?php  echo  $this->locale->_('component'); ?></a><br>





<?php


?>
<a href="../login/logout" ><button class="btn btn-danger"><?php 
             
                  echo  $this->locale->_('logout');
                
                  
                 ?></button></a>