
<?php
echo $this->tag->linkTo('addproduct','Add Product')."<br>";
echo $this->tag->linkTo('products','Products')."<br>";
echo $this->tag->linkTo('neworder','New Order')."<br>";
echo $this->tag->linkTo('orders','Orders')."<br>";
echo $this->tag->linkTo('settings','Settings')."<br>";
echo $this->tag->linkTo('component','Component')."<br>";

?>
<a href="../login/logout" ><button class="btn btn-danger">LogOut</button></a>